/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.firebase.views;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import com.mycompany.firebase.CRUD.CRUDFireStore;
import com.mycompany.firebase.CRUD.CRUDStorage;
import com.mycompany.firebase.conection.conexion;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ALEX
 */
public class editProduct extends javax.swing.JFrame {
        byte[] bytesImg = null;
        private String idProduct = null;
        private final String CollectionName = "products";
        private List<String> Datos = null;
        private List<String> CodesBar = null;
        private String oldTimeRefreshFStore;
        private String oldTimeRefreshStorage;

        /**
         * Creates new form editProduct
         */
        public editProduct(String idProduct) {

                this.idProduct = idProduct;
                Datos = CRUDFireStore.DatosProducto(idProduct);
                CodesBar = listaBarCodes();
                initComponents();
                CambiosIniciales();
                setLocationRelativeTo(null);
                LlenarDatosdelProducto();
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                lblImagen = new javax.swing.JLabel();
                cmboBarCode = new javax.swing.JComboBox<>();
                txtNombre = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                txtPrecio = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                btnAgregarBarCode = new javax.swing.JButton();
                spnStock = new javax.swing.JSpinner();
                jLabel1 = new javax.swing.JLabel();
                btnEliminarBarCode = new javax.swing.JButton();
                btnGuardar = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                lblImagen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseMoved(java.awt.event.MouseEvent evt) {
                                lblImagenMouseMoved(evt);
                        }
                });
                lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblImagenMouseClicked(evt);
                        }
                });

                cmboBarCode.setModel(
                                new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel2.setText("NOMBRE:");

                jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel3.setText("PRECIO:");

                jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel4.setText("STOCK:");

                jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel1.setText("CODIGOS DE BARRA:");

                btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btnGuardarMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addContainerGap()
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(btnAgregarBarCode,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                40,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(btnEliminarBarCode,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                40,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                false)
                                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                .addComponent(jLabel4,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                .addComponent(spnStock,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                72,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                .addComponent(jLabel3,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                63,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addGap(26, 26, 26)
                                                                                                                                                                                .addComponent(txtPrecio))
                                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                .addComponent(jLabel2,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                63,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addGap(26, 26, 26)
                                                                                                                                                                                .addComponent(txtNombre,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                261,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                                .addGap(18, 18, 18))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(21, 21, 21)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(cmboBarCode,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                254,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel1))
                                                                                                .addGap(114, 114, 114)))
                                                                .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(lblImagen,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                195,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(btnGuardar,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(28, 28, 28)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(txtNombre,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                31,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                31,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(txtPrecio,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                31,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel3,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                31,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel4,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                31,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(spnStock,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                29,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                28,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(lblImagen,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                207,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(3, 3, 3)
                                                                .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(btnEliminarBarCode,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                35,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(btnAgregarBarCode,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                35,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(cmboBarCode,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                35,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(btnGuardar,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                35,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(19, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void lblImagenMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblImagenMouseClicked
                if (evt.getClickCount() == 1) {
                        String url = abrirImagen();
                        bytesImg = ConvertImgtoByte(url);
                        lblImagen.setIcon(CrearImgJlabel(new ImageIcon(url), lblImagen));
                }

        }// GEN-LAST:event_lblImagenMouseClicked

        private void lblImagenMouseMoved(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblImagenMouseMoved
                lblImagen.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }// GEN-LAST:event_lblImagenMouseMoved

        private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnGuardarMouseClicked
                ActualizarProducto();
                dispose();
                new listProducts().setVisible(true);
        }// GEN-LAST:event_btnGuardarMouseClicked

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAgregarBarCode;
        private javax.swing.JButton btnEliminarBarCode;
        private javax.swing.JButton btnGuardar;
        private javax.swing.JComboBox<String> cmboBarCode;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lblImagen;
        private javax.swing.JSpinner spnStock;
        private javax.swing.JTextField txtNombre;
        private javax.swing.JTextField txtPrecio;
        // End of variables declaration//GEN-END:variables

        private void CambiosIniciales() {
                Color color;
                addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosing(WindowEvent evt) {
                                WindowCLosed(evt);
                        }
                });
                btnAgregarBarCode.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent evt) {
                                btnAgregarAction(evt);
                        }
                });
                btnEliminarBarCode.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent evt) {
                                btnEliminarBarCodeClick(evt);
                        }
                });

                if (Datos.get(2).equals("") || Datos.get(2) == null) {
                        lblImagen.setIcon(CrearImgJlabel(new ImageIcon("imgs/images.png"), lblImagen));
                } // borrar al terminar de validar el producto sin img

                // arreglos btnAgregarBarCode
                btnAgregarBarCode
                                .setIcon(CrearImgButton(new ImageIcon("imgs/agregarTransparente.png"),
                                                btnAgregarBarCode, 8, 8));
                color = new Color(0x07, 0x8C, 0x03);// color para el boton agregarBarCode
                btnAgregarBarCode.setBackground(color);
                // arreglos btnEliminarBarCode
                btnEliminarBarCode
                                .setIcon(CrearImgButton(new ImageIcon("imgs/eliminarTransparente.png"),
                                                btnEliminarBarCode, 12, 12));
                color = new Color(0x9F, 0x00, 0x00);// color para el boton eliminarBarCode
                btnEliminarBarCode.setBackground(color);
                // arreglos btnGuardar
                btnGuardar.setIcon(CrearImgButton(new ImageIcon("imgs/salvar.png"), btnGuardar, 7, 160));
                color = new Color(0x9F, 0x00, 0x00);// color para el boton guardar
                // color = new Color(0xFF, 0x00, 0x00);// color para el boton guardar
                btnGuardar.setBackground(color);
                cmboBarCode.removeAllItems();
                

                for (String codigo : CodesBar) {
                        if (!codigo.substring(0, 2).equals("IG")) {
                                cmboBarCode.addItem(codigo);
                        }
                }

        }

        private void WindowCLosed(WindowEvent evt) {
                dispose();
                new listProducts().setVisible(true);
        }

        private void btnAgregarAction(MouseEvent evt) {
                if (evt.getClickCount() == 1) {
                        String codigoNuevo = JOptionPane.showInputDialog("ingresar codigo de barras");
                        if (codigoNuevo != null) {
                                if (validarCodeBar(codigoNuevo)) {
                                        cmboBarCode.addItem(codigoNuevo);
                                } else {
                                        JOptionPane.showMessageDialog(this, "Codigo ya existe", "Advertencia!",
                                                        JOptionPane.ERROR_MESSAGE, null);
                                }
                        }
                        ;
                }
        }

        private void btnEliminarBarCodeClick(MouseEvent evt) {
                if (evt.getClickCount() == 1) {
                        EliminarCodeBar();
                }
        }

        /**
         * 
         * @param url        ruta de la imagen o la imagen
         * @param contenedor Jlabel que va a contener la imagen
         * @return returna la imagen ajustada al tamaño del Jlabel
         */
        private Icon CrearImgJlabel(ImageIcon img, JLabel contenedor) {
                Icon icono = new ImageIcon(
                                img.getImage().getScaledInstance(contenedor.getWidth(), contenedor.getHeight(),
                                                contenedor.getWidth()));
                return icono;
        }

        /**
         * 
         * @param url        ruta de la imagen o la imagen
         * @param contenedor JButton que va a contener la imagen
         * @return returna la imagen ajustada al tamaño del JButton
         */
        private Icon CrearImgButton(ImageIcon img, JButton contenedor, int reducirAlto, int reducirAncho) {
                Icon icono = new ImageIcon(
                                img.getImage().getScaledInstance(contenedor.getWidth() - reducirAncho,
                                                contenedor.getHeight() - reducirAlto, contenedor.getWidth()));
                return icono;
        }

        /**
         * 
         * @return agrega la img seleccionada al JlabelImg y retorna su url
         */
        private String abrirImagen() {
                // Crear un objeto JFileChooser
                JFileChooser fileChooser = new JFileChooser();

                // Mostrar el diálogo de selección de archivo
                int result = fileChooser.showOpenDialog(null);

                // Verificar si el usuario seleccionó un archivo
                if (result == JFileChooser.APPROVE_OPTION) {
                        // Obtener el archivo seleccionado
                        File selectedFile = fileChooser.getSelectedFile();

                        // Hacer algo con el archivo seleccionado (por ejemplo, mostrar su ruta)
                        return selectedFile.getAbsolutePath();
                } else {
                        return null;
                }
        }

        private byte[] ConvertImgtoByte(String url) {
                byte[] bytesImg = null;
                try {
                        bytesImg = Files.readAllBytes(Paths.get(url));
                } catch (Exception e) {
                        System.out.println("Error(converImgtoByte): " + e.getMessage());
                }
                return bytesImg;
        }

        private void LlenarDatosdelProducto() {

                txtNombre.setText(Datos.get(0));
                txtPrecio.setText(Datos.get(1));
                lblImagen.setIcon(
                                CrearImgJlabel(new ImageIcon(CRUDStorage.downloadImageBytes(Datos.get(2))), lblImagen));
                bytesImg = CRUDStorage.downloadImageBytes(Datos.get(2));
                spnStock.setValue(Integer.parseInt(Datos.get(3)));
                oldTimeRefreshFStore = Datos.get(4);
                oldTimeRefreshStorage = Datos.get(5);

        }

        /**
         * 
         * @return retorna una lista con los codigos de barra enviados desde
         *         listProducts del producto
         */
        private List<String> listaBarCodes() {
                int i = 0;
                int y = 3;
                List<String> lista = new ArrayList<>();
                if (idProduct.substring(0, 2).equals("cb")) {
                        for (char s : idProduct.toCharArray()) {
                                if (i < idProduct.length()) {
                                        if (idProduct.substring(i, i + 1).equals(",")) {
                                                lista.add(idProduct.substring(y, i));
                                                y = i + 1;
                                        }
                                        i++;
                                }
                        }
                        
                } else {
                        lista.add("IG:" + idProduct);
                }
                System.out.println(lista);
                return lista;
        }

        private boolean validarBarCodes() {
                if(IdModificado()){
                List<String> listaDocuments = CRUDFireStore.getAllDocuments(CollectionName);// lista que tiene todos los
                                                                                            // nombres de los documentos
                List<String> listaIdsBarCodes = new ArrayList<>();// lista que va a tener los nombres de los documentos
                                                                  // con cb: al principio
                List<String> CodigosBarraFirestore = new ArrayList<>();// lista con todos los barcodes de los productos
                                                                       // en la firestore
                int validar = 0;
                if (listaDocuments == null) {
                        return false;
                } else if (listaDocuments.size() == 0 || cmboBarCode.getItemCount() == 0) {// tamaño de la lista de 0
                        return true;
                } else {// tamaño de la lista mayor a 0
                        for (String document : listaDocuments) {
                                if (document.substring(0, 3).equals("cb:")) {
                                        listaIdsBarCodes.add(document);
                                }
                        }
                        for (String IdsBarCodes : listaIdsBarCodes) {
                                int i = 0;
                                int y = 3;
                                for (char s : IdsBarCodes.toCharArray()) {
                                        if (i < IdsBarCodes.length()) {
                                                if (IdsBarCodes.substring(i, i + 1).equals(",")) {
                                                        // lleno una lista con todos los codigos de barra de los
                                                        // productos en la firestore
                                                        CodigosBarraFirestore.add(IdsBarCodes.substring(y, i));
                                                        y = i + 1;
                                                }
                                                i++;
                                        }
                                }
                        }

                        for (String r:CodeBarsValidos()) {// valido si el codigo de barra ya existe
                                                                              // en la lista del producto actual
                                for (String s : CodigosBarraFirestore)
                                        if (r.equals(s)) {
                                                validar = 1;
                                        }
                        }
                        if (validar == 1) {
                                System.out.println("validar =1");
                                return false;
                        } else {
                                return true;
                        }
                }
        }else{
                return false;
        }
        }

        private boolean validarCodeBar(String CodeBar) {
                List<String> listaDocuments = CRUDFireStore.getAllDocuments(CollectionName);// lista que tiene todos los
                                                                                            // nombres de los documentos
                List<String> listaIdsBarCodes = new ArrayList<>();// lista que va a tener los nombres de los documentos
                                                                  // con cb: al principio
                List<String> CodigosBarraFirestore = new ArrayList<>();// lista con todos los barcodes de los productos
                                                                       // en la firestore
                int validar = 0;
                if (listaDocuments.size() >= 1) {// tamaño de la lista mayor a 0
                        for (String document : listaDocuments) {
                                if (document.substring(0, 3).equals("cb:")) {
                                        listaIdsBarCodes.add(document);
                                }
                        }
                        for (String IdsBarCodes : listaIdsBarCodes) {
                                int i = 0;
                                int y = 3;
                                for (char s : IdsBarCodes.toCharArray()) {
                                        if (i < IdsBarCodes.length()) {
                                                if (IdsBarCodes.substring(i, i + 1).equals(",")) {
                                                        CodigosBarraFirestore.add(IdsBarCodes.substring(y, i));// lleno
                                                                                                               // una
                                                                                                               // lista
                                                        // con todos los
                                                        // codigos de
                                                        // barra de los
                                                        // productos en la
                                                        // firestore
                                                        y = i + 1;
                                                }
                                                i++;
                                        }
                                }
                        }
                        for (String code : CodigosBarraFirestore) {// valido si el codigo de barra ya existe en la base
                                                                   // de datos de firestore
                                if (CodeBar.equals(code)) {
                                        validar = 1;
                                }
                        }
                        for (int i = 0; i < cmboBarCode.getItemCount(); i++) {// valido si el codigo de barra ya existe
                                                                              // en la lista del producto actual
                                if (CodeBar.equals(cmboBarCode.getItemAt(i))) {
                                        validar = 1;
                                }
                        }
                        if (validar == 1) {
                                return false;
                        } else {
                                return true;
                        }

                } else if (listaDocuments.size() == 0) {// tamaño de la lista de 0
                        return true;
                } else {
                        return false;
                }

        }

        private void EliminarCodeBar() {

                try {

                        int i = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar este codigo",
                                        "Advertencia!", JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION, null);
                        if (i == 0) {
                                cmboBarCode.removeItemAt(cmboBarCode.getSelectedIndex());
                        } else {

                        }

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Causa: " + e.getMessage(), "Fail!",
                                        JOptionPane.ERROR_MESSAGE, null);
                }

        }

        private void ActualizarProducto() {
                List<String> NewlistBarCode = new ArrayList<>();
                if (cmboBarCode.getItemCount() > 0) {
                        for (int i = 0; i < cmboBarCode.getItemCount(); i++) {
                                NewlistBarCode.add(cmboBarCode.getItemAt(i));
                        }
                }
                boolean cambiosId = CRUDFireStore.validarCambiosId(idProduct);
                boolean cambiosDatos = CRUDFireStore.validarCambiosDatos(idProduct, oldTimeRefreshFStore);
                boolean cambiosImg = CRUDStorage.validarCambioimg(Datos.get(2), oldTimeRefreshStorage);
                boolean validarBarCode = validarBarCodes();
                System.out.println("id: " + cambiosId);
                System.out.println("datos: " + cambiosDatos);
                System.out.println("Img: " + cambiosImg);
                System.out.println("BarCode: " + validarBarCode);
                if (cambiosId && cambiosDatos && cambiosImg && validarBarCode) {
                        CRUDFireStore.editarProduct(Double.parseDouble(txtPrecio.getText()), bytesImg,
                                        Integer.parseInt(spnStock.getValue().toString()), CodesBar, NewlistBarCode,
                                        Datos.get(2), txtNombre.getText());
                } else {
                        JOptionPane.showMessageDialog(this, "el producto a sido modificado recientemente");
                }

        }

        /**
         * 
         * @return retorna una lista con los codigos de barra que si se van a revisar en
         *         la base de datos
         */
        private List<String> CodeBarsValidos() {
                List<String> listaSalida = new ArrayList<>();
                
                        
                        for (int i = 0; i < cmboBarCode.getItemCount(); i++) {
                                boolean repetido=false;
                                for (String s : CodesBar) {
                                if (s.equals(cmboBarCode.getItemAt(i))) {
                                        repetido=true;
                                }
                        }
                        if(!repetido){
                                listaSalida.add(cmboBarCode.getItemAt(i));
                        }
                }
                System.out.println("*****************************************************");
                for(String as:listaSalida){
                        System.out.println("codigo:"+as);
                        
                }
                System.out.println("*****************************************************");
                return listaSalida;
        }

        /**
         * 
         * @return retorna true si el id no a sido modificado mientras te encuentras en la ventana de actualizar producto si no retorna false
         */
        private boolean IdModificado() {
                int CodigoEncontrado = 0;
                for (String s : CRUDFireStore.getAllDocuments(CollectionName)) {// valido si el id aun existe en la base
                                                                                // de datos
                        if (s.equals(idProduct)) {
                                CodigoEncontrado = 1;
                        }
                }
                if (CodigoEncontrado == 1) {
                        return true;
                } else {
                        

                        return false;
                }
        }

}
