/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.firebase.views;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import com.google.cloud.firestore.Firestore;
import com.mycompany.firebase.CRUD.CRUDFireStore;
import com.mycompany.firebase.conection.ConexionFactory;

/**
 *
 * @author ALEX
 */
public class newProduct extends javax.swing.JFrame {
        String urlImgLocal = "imgs/images.png";
        List<String> BarCodes;
        private Connection conexionSql = null;
        
        private CRUDFireStore firebaseCRUD = null;

        /**
         * Creates new form newProduct
         */
        public newProduct() {
                initComponents();
                conexionSql = ConexionFactory.getConexionSqlServer();// iniciando una conexion a SQlServer
                firebaseCRUD = CRUDFireStore.getCRUDFireStore();// creando una instancia del CURDFirestore para usar
                                                                   // sus metodos
                CambiosIniciales();
                setLocationRelativeTo(null);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                txtNombre = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                txtPrecio = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                spnStock = new javax.swing.JSpinner();
                btnGuardar = new javax.swing.JButton();
                lblImagen = new javax.swing.JLabel();
                btnEliminarBarCode = new javax.swing.JButton();
                btnAgregarBarCode = new javax.swing.JButton();
                cmboBarCode = new javax.swing.JComboBox<>();
                jLabel1 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel2.setText("NOMBRE:");

                jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel3.setText("PRECIO:");

                jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel4.setText("STOCK:");

                btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btnGuardarMouseClicked(evt);
                        }
                });

                lblImagen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseMoved(java.awt.event.MouseEvent evt) {
                                lblImagenMouseMoved(evt);
                        }
                });
                lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblImagenMouseClicked(evt);
                        }
                });

                cmboBarCode.setModel(
                                new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel1.setText("CODIGOS DE BARRA:");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addContainerGap()
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(btnAgregarBarCode,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                40,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(btnEliminarBarCode,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                40,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                false)
                                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                .addComponent(jLabel4,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                .addComponent(spnStock,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                72,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                .addComponent(jLabel3,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                63,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addGap(26, 26, 26)
                                                                                                                                                                                .addComponent(txtPrecio))
                                                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                                                                .addComponent(jLabel2,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                63,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addGap(26, 26, 26)
                                                                                                                                                                                .addComponent(txtNombre,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                261,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                                .addGap(18, 18, 18))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(21, 21, 21)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(cmboBarCode,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                254,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel1))
                                                                                                .addGap(114, 114, 114)))
                                                                .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(lblImagen,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                195,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(btnGuardar,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(28, 28, 28)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(txtNombre,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                31,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                31,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(txtPrecio,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                31,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel3,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                31,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel4,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                31,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(spnStock,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                29,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                28,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(lblImagen,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                207,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(3, 3, 3)
                                                                .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(btnEliminarBarCode,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                35,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(btnAgregarBarCode,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                35,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(cmboBarCode,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                35,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(btnGuardar,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                35,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(19, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnGuardarMouseClicked
                boolean crear = CrearProducto();
                if (crear) {
                        dispose();
                        new listProducts().setVisible(true);
                }

        }// GEN-LAST:event_btnGuardarMouseClicked

        private void lblImagenMouseMoved(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblImagenMouseMoved
                lblImagen.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }// GEN-LAST:event_lblImagenMouseMoved

        private void lblImagenMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblImagenMouseClicked
                // usar el metodo lblImagenClick()
        }// GEN-LAST:event_lblImagenMouseClicked

        private void lblImagenClick(MouseEvent evt) {
                if (evt.getClickCount() == 1) {

                        System.out.println("Respuesta(1): " + urlImgLocal);
                        String ImgLocal = abrirImagen();

                        if (ImgLocal != null) {
                                urlImgLocal = ImgLocal;
                                System.out.println("url: " + urlImgLocal);
                                lblImagen.setIcon(CrearImgJLabel(new ImageIcon(urlImgLocal), lblImagen));

                        }
                        System.out.println("Respuesta(2): " + urlImgLocal);
                }

        }

        private void btnEliminarBarCodeClick(MouseEvent evt) {
                if (evt.getClickCount() == 1) {
                        EliminarCodeBar();
                }
        }

        private void btnAgregarAction(MouseEvent evt) {
                if (evt.getClickCount() == 1) {
                        String codigoNuevo = JOptionPane.showInputDialog("ingresar codigo de barras");
                        if (codigoNuevo != null) {
                                if (validarCodeBar(codigoNuevo)) {
                                        cmboBarCode.addItem(codigoNuevo);
                                } else {
                                        JOptionPane.showMessageDialog(this, "Codigo ya existe", "Advertencia!",
                                                        JOptionPane.ERROR_MESSAGE, null);
                                }
                        }
                        ;
                }
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAgregarBarCode;
        private javax.swing.JButton btnEliminarBarCode;
        private javax.swing.JButton btnGuardar;
        private javax.swing.JComboBox<String> cmboBarCode;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lblImagen;
        private javax.swing.JSpinner spnStock;
        private javax.swing.JTextField txtNombre;
        private javax.swing.JTextField txtPrecio;
        // End of variables declaration//GEN-END:variables

        private void CambiosIniciales() {
                Color color;
                addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosing(WindowEvent evt) {
                                dispose();
                                new listProducts().setVisible(true);
                        }
                });
                lblImagen.setIcon(CrearImgJLabel(new ImageIcon("imgs/images.png"), lblImagen));
                lblImagen.addMouseMotionListener(new MouseMotionAdapter() {
                        @Override
                        public void mouseMoved(MouseEvent evt) {
                                lblImagenMouseMoved(evt);
                        }
                });
                lblImagen.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent evt) {
                                lblImagenClick(evt);
                        }
                });
                btnEliminarBarCode.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent evt) {
                                btnEliminarBarCodeClick(evt);
                        }
                });
                btnAgregarBarCode.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent evt) {
                                btnAgregarAction(evt);
                        }
                });

                // arreglos btnAgregarBarCode
                btnAgregarBarCode
                                .setIcon(CrearImgButton(new ImageIcon("imgs/agregarTransparente.png"),
                                                btnAgregarBarCode, 8, 8));
                color = new Color(0x07, 0x8C, 0x03);// color para el boton agregarBarCode
                btnAgregarBarCode.setBackground(color);
                // arreglos btnEliminarBarCode
                btnEliminarBarCode
                                .setIcon(CrearImgButton(new ImageIcon("imgs/eliminarTransparente.png"),
                                                btnEliminarBarCode, 12, 12));
                color = new Color(0x9F, 0x00, 0x00);// color para el boton eliminarBarCode
                btnEliminarBarCode.setBackground(color);
                // arreglos btnGuardar
                btnGuardar.setIcon(CrearImgButton(new ImageIcon("imgs/salvar.png"), btnGuardar, 7, 160));
                color = new Color(0x9F, 0x00, 0x00);// color para el boton guardar
                // color = new Color(0xFF, 0x00, 0x00);// color para el boton guardar
                btnGuardar.setBackground(color);
                cmboBarCode.removeAllItems();
        }

        /**
         * 
         * @param url        ruta de la imagen o la imagen
         * @param contenedor Jlabel que va a contener la imagen
         * @return returna la imagen ajustada al tamaño del Jlabel
         */
        private Icon CrearImgJLabel(ImageIcon img, JLabel contenedor) {

                Icon icono = new ImageIcon(
                                img.getImage().getScaledInstance(contenedor.getWidth(), contenedor.getHeight(),
                                                contenedor.getWidth()));
                return icono;

        }

        /**
         * 
         * @param url        ruta de la imagen o la imagen
         * @param contenedor JButton que va a contener la imagen
         * @return returna la imagen ajustada al tamaño del JButton
         */
        private Icon CrearImgButton(ImageIcon img, JButton contenedor, int reducirAlto, int reducirAncho) {
                Icon icono = new ImageIcon(
                                img.getImage().getScaledInstance(contenedor.getWidth() - reducirAncho,
                                                contenedor.getHeight() - reducirAlto, contenedor.getWidth()));
                return icono;
        }

        /**
         * 
         * @return agrega la img seleccionada al JlabelImg y retorna su url
         */
        private String abrirImagen() {
                // Crear un objeto JFileChooser
                JFileChooser fileChooser = new JFileChooser();

                // Mostrar el diálogo de selección de archivo
                int result = fileChooser.showOpenDialog(null);

                // Verificar si el usuario seleccionó un archivo
                if (result == JFileChooser.APPROVE_OPTION) {
                        // Obtener el archivo seleccionado
                        File selectedFile = fileChooser.getSelectedFile();

                        // Hacer algo con el archivo seleccionado (por ejemplo, mostrar su ruta)
                        return selectedFile.getAbsolutePath();
                } else {
                        return null;
                }
        }

        private boolean validarBarCodes() {// FALTA COMPLETAR LA LOGICA Y REVISAR TBM EN EL FORMULARIO DE EDITAR
                List<String> listaDocuments = firebaseCRUD.getAllDocuments();// lista que tiene todos los
                                                                                            // nombres de los documentos
                List<String> listaIdsBarCodes = new ArrayList<>();// lista que va a tener los nombres de los documentos
                                                                  // con cb: al principio
                List<String> CodigosBarraFirestore = new ArrayList<>();// lista con todos los barcodes de los productos
                                                                       // en la firestore
                int validar = 0;
                if (listaDocuments == null) {
                        return false;
                } else if (listaDocuments.size() == 0 || cmboBarCode.getItemCount() == 0) {// tamaño de la lista de 0
                        return true;
                } else {// tamaño de la lista mayor a 0
                        for (String document : listaDocuments) {
                                if (document.substring(0, 3).equals("cb:")) {
                                        listaIdsBarCodes.add(document);
                                }
                        }
                        for (String IdsBarCodes : listaIdsBarCodes) {
                                int i = 0;
                                int y = 3;
                                for (char s : IdsBarCodes.toCharArray()) {
                                        if (i < IdsBarCodes.length()) {
                                                if (IdsBarCodes.substring(i, i + 1).equals(",")) {
                                                        // lleno una lista con todos los codigos de barra de los
                                                        // productos en la firestore
                                                        CodigosBarraFirestore.add(IdsBarCodes.substring(y, i));
                                                        y = i + 1;
                                                }
                                                i++;
                                        }
                                        // esto solo es para que no me aparesca como que no uso la variable s no tiene
                                        // efecto en la logica
                                        if (i == 0) {
                                                System.out.print(s);
                                        }
                                }
                        }
                        for (int i = 0; i < cmboBarCode.getItemCount(); i++) {// valido si el codigo de barra ya existe
                                                                              // en la lista del producto actual
                                for (String s : CodigosBarraFirestore)
                                        if (cmboBarCode.getItemAt(i).equals(s)) {
                                                validar = 1;
                                        }
                        }
                        if (validar == 1) {
                                return false;
                        } else {
                                return true;
                        }
                }
        }

        private boolean CrearProducto() {
                List<String> listBarCodes = new ArrayList<>();
                if (cmboBarCode.getItemCount() > 0) {
                        for (int i = 0; i < cmboBarCode.getItemCount(); i++) {
                                listBarCodes.add(cmboBarCode.getItemAt(i));
                        }
                }
                if (validarBarCodes()) {

                        firebaseCRUD.uploaderOnFireStore(txtNombre.getText(), Double.parseDouble(txtPrecio.getText()),
                                        urlImgLocal, Integer.parseInt(spnStock.getValue().toString()), listBarCodes);
                        return true;
                } else {
                        JOptionPane.showMessageDialog(this, "Uno de los codigos de barra ya existe.", "ERROR!",
                                        JOptionPane.ERROR_MESSAGE, null);
                        return false;
                }

        }

        private void EliminarCodeBar() {

                try {

                        int i = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar este codigo",
                                        "Advertencia!", JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION, null);
                        if (i == 0) {
                                cmboBarCode.removeItemAt(cmboBarCode.getSelectedIndex());
                        } else {

                        }

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Causa: " + e.getMessage(), "Fail!",
                                        JOptionPane.ERROR_MESSAGE, null);
                }

        }

        private boolean validarCodeBar(String CodeBar) {
                List<String> listaDocuments = firebaseCRUD.getAllDocuments();// lista que tiene todos los
                                                                                            // nombres de los documentos
                List<String> listaIdsBarCodes = new ArrayList<>();// lista que va a tener los nombres de los documentos
                                                                  // con cb: al principio
                List<String> CodigosBarraFirestore = new ArrayList<>();// lista con todos los barcodes de los productos
                                                                       // en la firestore
                int validar = 0;
                if (listaDocuments.size() >= 1) {// tamaño de la lista mayor a 0
                        for (String document : listaDocuments) {
                                if (document.substring(0, 3).equals("cb:")) {
                                        listaIdsBarCodes.add(document);
                                }
                        }
                        for (String IdsBarCodes : listaIdsBarCodes) {
                                int i = 0;
                                int y = 3;
                                for (char s : IdsBarCodes.toCharArray()) {
                                        if (i < IdsBarCodes.length()) {
                                                if (IdsBarCodes.substring(i, i + 1).equals(",")) {
                                                        CodigosBarraFirestore.add(IdsBarCodes.substring(y, i));// lleno
                                                                                                               // una
                                                                                                               // lista
                                                        // con todos los
                                                        // codigos de
                                                        // barra de los
                                                        // productos en la
                                                        // firestore
                                                        y = i + 1;
                                                }
                                                i++;
                                        }
                                        // esto solo es para que no me aparesca como que no uso la variable s no tiene
                                        // efecto en la logica
                                        if (i == 0) {
                                                System.out.print(s);
                                        }
                                }
                        }
                        for (String code : CodigosBarraFirestore) {// valido si el codigo de barra ya existe en la base
                                                                   // de datos de firestore
                                if (CodeBar.equals(code)) {
                                        validar = 1;
                                }
                        }
                        for (int i = 0; i < cmboBarCode.getItemCount(); i++) {// valido si el codigo de barra ya existe
                                                                              // en la lista del producto actual
                                if (CodeBar.equals(cmboBarCode.getItemAt(i))) {
                                        validar = 1;
                                }
                        }
                        if (validar == 1) {
                                return false;
                        } else {
                                return true;
                        }

                } else if (listaDocuments.size() == 0) {// tamaño de la lista de 0
                        return true;
                } else {
                        return false;
                }

        }

}